# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 611, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelUsenameIstagram = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelUsenameIstagram.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelUsenameIstagram.setObjectName("labelUsenameIstagram")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelUsenameIstagram)
        self.lineEditUsernameInstagram = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditUsernameInstagram.setObjectName("lineEditUsernameInstagram")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditUsernameInstagram)
        self.labelJumlahFollower = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelJumlahFollower.setObjectName("labelJumlahFollower")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelJumlahFollower)
        self.lineEditJumlahFollower = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditJumlahFollower.setObjectName("lineEditJumlahFollower")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditJumlahFollower)
        self.labelJumlahPosting = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelJumlahPosting.setObjectName("labelJumlahPosting")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelJumlahPosting)
        self.lineEditJumlahPosting = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditJumlahPosting.setObjectName("lineEditJumlahPosting")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditJumlahPosting)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonSimpan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSimpan.setObjectName("pushButtonSimpan")
        self.horizontalLayout_2.addWidget(self.pushButtonSimpan)
        self.pushButtonHapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonHapus.setObjectName("pushButtonHapus")
        self.horizontalLayout_2.addWidget(self.pushButtonHapus)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.pushButtonHapus.clicked.connect(self.tableWidget.clearContents) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Data Instagram 232102020"))
        self.labelUsenameIstagram.setText(_translate("Form", "Usename Instagram"))
        self.labelJumlahFollower.setText(_translate("Form", "Jumlah Follower"))
        self.labelJumlahPosting.setText(_translate("Form", "Jumlah Posting"))
        self.pushButtonSimpan.setText(_translate("Form", "Simpan"))
        self.pushButtonHapus.setText(_translate("Form", "Hapus"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Username Instagram"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Jumlah Follower"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Jumlah Posting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
